# A workflow with caching 
#
name: DictionaryLayoutCheck

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
            - '.github/**'

jobs:
#  uncache:
#    runs-on: ubuntu-latest
#
#    steps:
#       - name: Get the cache
#         uses: actions/cache@v2
#         id: cache
#         with:
#                 path: /root/.julia
#         key: ${{ runner.os }}-julia

  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
                version: '1.6'

      - name: Install Julia packages
        run: |
               julia -e 'import Pkg;Pkg.add("CrystalInfoFramework");Pkg.add("Lerche")'

      - name: checkout
        uses: actions/checkout@v2
        with:
                path: main
      - name: checkout julia tools
        uses: actions/checkout@v2
        with:
                repository: jamesrhester/julia_cif_tools
                path: julia_cif_tools

      - name: Checkout CIF master files
        uses: actions/checkout@v2
        with:
                repository: COMCIFS/cif_core
                path: cif_core


  check:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: one_dict_layout
        run: |
               echo "Checking $file"
